<?php

require_once __DIR__ . "/config.php";
////////The God Hacker//////
//Creator: @GodHacker_SC////
error_reporting(0);

set_time_limit(0);

flush();
##------------------------------##
define('API_KEY',$BOT_TOKEN);

ini_set("log_errors","off");
function Bot($method,$datas=[]){
$url = "https://api.telegram.org/bot".API_KEY."/".$method;
$ch = curl_init();
curl_setopt($ch,CURLOPT_URL,$url);
curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
curl_setopt($ch,CURLOPT_POSTFIELDS,$datas);
$res = curl_exec($ch);
if(curl_error($ch)){
var_dump(curl_error($ch));
}else{
return json_decode($res);
}
}
$update = json_decode(file_get_contents('php://input'));
$message = $update->message;
$chat_id = $message->chat->id;
$message_id = $message->message_id;
$from_id = $message->from->id;
$first_name = $message->from->first_name;
$last_name = $message->from->last_name;
$username = $message->from->username;
$msg = $message->text;

if($msg == '/start'){
Bot('sendmessage',[
'chat_id'=>$chat_id,
'text'=> "***Hello 👋 $first_name,

I'm a Random Data Generator Bot. I can Generate Random Data Of Usa Citizens

Type /gen To Generate Random Datas***",
'parse_mode'=>"MarkDown",

]);

}else{
$get = json_decode(file_get_contents('https://randomuser.me/api/1.2/?nat=us'),true);

$first = $get['results'][0]['name']['first'];
$last =  $get['results'][0]['name']['last'];
$gend =  $get['results'][0]['gender'];
$street = $get['results'][0]['location']['street'];
$city = $get['results'][0]['location']['city'];
$state = $get['results'][0]['location']['state'];
$email = $get['results'][0]['email'];
$dob = $get['results'][0]['dob']['date'];
$age = $get['results'][0]['dob']['age'];
$cell = $get['results'][0]['cell'];
$phone = $get['results'][0]['phone'];
$ssn = $get['results'][0]['id']['value'];

if($msg == '/gen')
Bot('sendmessage',[
'chat_id'=>$chat_id,
'text'=> "***🌐 Generated Data 🌐***

***FIRST NAME***: `$first $last`
***GENDER*** : `$gend`
***STREET*** : `$street`
***CITY*** : `$city`
***STATE*** : `$state`
***DATE OF BIRTH*** : `$dob`
***AGE*** : `$age`
***SSN*** : `$ssn`
***CELL*** : `$cell`
***PHONE*** : `$phone`
***EMAIL*** : `$first.$last@gmail.com,`
***GENERATED BY*** : @$username


***GENERATED FROM:- $BOT_USERNAME***",
'parse_mode'=>"MarkDown",
]);
}
